# Generated by Django 6.0.6 on 2026-07-09 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NEW_ORDER', 'طلب جديد'), ('ORDER_NEEDS_APPROVAL', 'طلب يحتاج موافقتك على تعديل'), ('ORDER_CONFIRMED', 'تم تأكيد الطلب'), ('ORDER_REJECTED', 'تم رفض الطلب'), ('ORDER_DELIVERED', 'تم تسليم الطلب'), ('CLIENT_APPROVED_AMENDMENT', 'العميل وافق على التعديل'), ('CLIENT_REJECTED_AMENDMENT', 'العميل رفض التعديل'), ('NEW_CLIENT_REGISTRATION', 'طلب تسجيل عميل جديد')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('url_name', models.CharField(blank=True, max_length=100)),
                ('url_kwargs', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
