# Generated by Django 6.0.6 on 2026-07-30 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('activity_type', models.CharField(choices=[('CALL', 'مكالمة هاتفية'), ('VISIT', 'زيارة'), ('PAYMENT_FOLLOWUP', 'متابعة سداد'), ('OTHER', 'أخرى')], default='CALL', max_length=20, verbose_name='نوع المتابعة')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='تفاصيل مختصرة')),
                ('due_date', models.DateField(db_index=True, verbose_name='تاريخ الاستحقاق')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups_assigned', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups_created', to=settings.AUTH_USER_MODEL)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups_completed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'متابعة',
                'verbose_name_plural': 'المتابعات',
                'ordering': ['due_date', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='followups_f_content_25d7d9_idx')],
            },
        ),
    ]
