# Generated by Django 6.0.6 on 2026-07-05 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_level_inventory'),
        ('products', '0008_remove_productunit_allow_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(help_text='بوحدة "الوحدة" المختارة أعلاه، وليس بالضرورة بالقطعة — يقوم النظام بتحويلها تلقائيًا.', verbose_name='الكمية (بوحدة الحركة)'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit',
            field=models.ForeignKey(help_text='الوحدة التي سُجّلت بها الحركة (كرتونة/قطعة) — الكمية أدناه بوحدة هذه الوحدة.', on_delete=django.db.models.deletion.PROTECT, to='products.productunit', verbose_name='الوحدة'),
        ),
    ]
