# Generated by Django 6.0.6 on 2026-07-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockmovement_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='is_available',
            field=models.BooleanField(default=True, help_text='يتم تحديثه تلقائياً عند انخفاض الكمية، أو يمكن التحكم فيه يدوياً', verbose_name='متوفر في المتجر'),
        ),
    ]
