# Generated by Django 6.0.6 on 2026-08-10 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_is_available'),
        ('products', '0021_remove_product_variant_group_remove_product_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر القديم')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الجديد')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='inventory.inventory')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productunit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'تغيير سعر',
                'verbose_name_plural': 'تغييرات الأسعار',
                'ordering': ['-created_at'],
            },
        ),
    ]
