# Generated by Django 6.0.6 on 2026-08-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoiceitem_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='مسودة'),
        ),
    ]
