# Generated by Django 6.0.6 on 2026-07-04 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INVOICE', 'فاتورة'), ('PAYMENT', 'دفعة'), ('ADJUSTMENT', 'تسوية')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='موجب = بيزوّد مديونية العميل، سالب = بيقلّلها.', max_digits=12)),
                ('method', models.CharField(blank=True, choices=[('CASH', 'كاش'), ('TRANSFER', 'تحويل بنكي'), ('CHEQUE', 'شيك')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='account_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_transactions', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'حركة حساب',
                'verbose_name_plural': 'حركات الحسابات',
                'ordering': ['created_at'],
            },
        ),
    ]
