# Generated by Django 6.0.6 on 2026-07-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_reports', 'عرض قسم التقارير والتحليلات')],
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
