# Generated by Django 6.0.6 on 2026-07-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBackupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage_backup', 'تشغيل نسخة احتياطية يدويًا وعرض تفاصيل الأخطاء')],
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
