# Generated by Django 6.0.6 on 2026-07-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_backfill_original_item_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='purchase_mode',
            field=models.CharField(choices=[('CARTON', 'بالكرتونة'), ('PIECE', 'بالقطعة')], default='CARTON', help_text='بالكرتونة أو بالقطعة (للوحدات القابلة للتجزئة بس) — بيحدد وحدة quantity أعلاه.', max_length=6, verbose_name='وضع الشراء'),
        ),
    ]
