# Generated by Django 6.0.6 on 2026-07-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_discount_percent_orderitem_public_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='show_discounted_prices',
            field=models.BooleanField(default=False, help_text='لو مفعّل، هيظهر للعميل في صفحات المتجر سعر المخزن (بعد خصم نوع حسابه) جنب سعر الجمهور. اتركه غير مفعّل لحين التأكد من صحة أسعار الخصم الجديدة — سعر الجمهور بيظهر دايمًا بغض النظر عن هذا الإعداد.', verbose_name='إظهار سعر المخزن في المتجر'),
        ),
    ]
