# Generated by Django 6.0.6 on 2026-07-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_siteconfig_show_discounted_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'في الانتظار'), ('NEEDS_APPROVAL', 'بانتظار موافقتك على التعديل'), ('CONFIRMED', 'مؤكد'), ('REJECTED', 'مرفوض'), ('DELIVERED', 'تم التسليم')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
