# Generated by Django 6.0.6 on 2026-07-23 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_viewed_by_staff'),
        ('products', '0015_productunit_cost_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='اسم الطلبية')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سلة',
                'verbose_name_plural': 'السلال',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productunit')),
            ],
            options={
                'verbose_name': 'صنف في السلة',
                'verbose_name_plural': 'أصناف السلة',
                'constraints': [models.UniqueConstraint(fields=('cart', 'product_unit'), name='unique_product_unit_per_cart')],
            },
        ),
    ]
