# Generated by Django 6.0.6 on 2026-07-31 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_cart_cartitem'),
        ('products', '0017_extract_size_from_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='min_order_amount_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأدنى وقت إرسال الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_service_fee',
            field=models.BooleanField(default=False, verbose_name='صنف خدمي (بدون مخزون)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='service_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم الخدمة'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productunit'),
        ),
    ]
