# Generated by Django 6.0.6 on 2026-08-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_systembackupaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnsAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_returns', 'إنشاء إشعار مرتجع (مرتجع بعد التأكيد/التسليم)')],
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
