# Generated by Django 6.0.6 on 2026-08-12 01:28

import django.core.validators
import django.db.models.deletion
import studio.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='studio/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), studio.validators.validate_image_size], verbose_name='الصورة')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='studio/thumbnails/%Y/%m/', verbose_name='الصورة المصغّرة')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_images_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='رفعها')),
            ],
            options={
                'verbose_name': 'صورة استوديو',
                'verbose_name_plural': 'صور الاستوديو',
                'ordering': ['-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['-uploaded_at'], name='studio_stud_uploade_4efc6b_idx')],
            },
        ),
    ]
