# Generated by Django 6.0.6 on 2026-08-12 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مجلد استوديو',
                'verbose_name_plural': 'مجلدات الاستوديو',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='studioimage',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='studio.studiofolder', verbose_name='المجلد'),
        ),
        migrations.AddIndex(
            model_name='studioimage',
            index=models.Index(fields=['folder'], name='studio_stud_folder__2b6a19_idx'),
        ),
    ]
