# Generated by Django 6.0.6 on 2026-08-12 07:57
#
# اكتشفناها أول مرة نُشغّل فيها Django فعليًا على المشروع (مش عملي في
# جلسات العمل السابقة — راجع ملاحظات المرحلة 6 في STUDIO_PLAN.md، "migration
# 0002 مكتوبة يدويًا لأن Django مش متاح"). اسم الـ index اللي اتكتب يدويًا
# هناك ('studio_stud_folder__2b6a19_idx') ما كانش نفس الاسم اللي خوارزمية
# Django بتولّده فعليًا لنفس الحقل — فرق تافه (hash مختلف)، بلا أي أثر
# على السلوك أو البيانات، بس كان بيمنع `makemigrations --check --dry-run`
# من الرجوع نضيف. RenameIndex بس، بلا أي تغيير في البيانات.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_studiofolder_studioimage_folder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studioimage',
            new_name='studio_stud_folder__f5144d_idx',
            old_name='studio_stud_folder__2b6a19_idx',
        ),
    ]
