# Generated by Django 6.0.6 on 2026-07-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTypeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('PHARMACY', 'صيدلية'), ('HOSPITAL', 'مستشفى'), ('CLINIC', 'عيادة'), ('OTHER', 'أخرى')], max_length=20, unique=True)),
                ('is_wholesale', models.BooleanField(default=False, help_text='لو مفعّل، أي حساب جديد من النوع ده هياخد سعر الجملة تلقائيًا.', verbose_name='جملة افتراضيًا')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='بتتطبق على سعر القطعة (unit_price) لو النوع ده جملة.', max_digits=5, verbose_name='نسبة الخصم الافتراضية (%)')),
            ],
            options={
                'verbose_name': 'إعداد تسعير نوع النشاط',
                'verbose_name_plural': 'إعدادات تسعير أنواع النشاط',
            },
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='custom_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سيبها فاضية لو عايز الحساب ياخد نسبة نوع النشاط الافتراضية.', max_digits=5, null=True, verbose_name='نسبة خصم مخصصة لهذا الحساب (%)'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='is_wholesale_override',
            field=models.BooleanField(blank=True, help_text='سيبها فاضية لو عايز الحساب يتبع إعداد نوع النشاط تلقائيًا.', null=True, verbose_name='تخصيص جملة/قطاعي لهذا الحساب'),
        ),
    ]
