# Generated by Django 6.0.6 on 2026-07-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accounttype_delete_businesstypesetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='لو محدّد، يُستخدم بدل القيمة العامة للموقع لهذا العميل فقط. اتركه فارغًا لاستخدام القيمة العامة (SiteConfig)، أو صفر لإلغاء الحد الأدنى لهذا العميل تحديدًا.', max_digits=10, null=True, verbose_name='الحد الأدنى لقيمة الطلب (مخصّص)'),
        ),
    ]
