# Generated by Django 6.0.6 on 2026-08-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_pricechange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='reserved',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'وارد'), ('OUT', 'صادر')], max_length=13),
        ),
    ]
