# Generated by Django 6.0.6 on 2026-07-27 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الوسم')),
                ('color', models.CharField(choices=[('gray', 'رمادي'), ('red', 'أحمر'), ('orange', 'برتقالي'), ('yellow', 'أصفر'), ('green', 'أخضر'), ('blue', 'أزرق'), ('purple', 'بنفسجي')], default='gray', max_length=10, verbose_name='اللون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'وسم',
                'verbose_name_plural': 'الوسوم',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_items_created', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='tags.tag')),
            ],
            options={
                'verbose_name': 'وسم على عنصر',
                'verbose_name_plural': 'وسوم العناصر',
                'ordering': ['tag__name'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='tags_tagged_content_eaa81e_idx')],
                'constraints': [models.UniqueConstraint(fields=('tag', 'content_type', 'object_id'), name='unique_tag_per_item')],
            },
        ),
    ]
