"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
from django.utils.csp import CSP
SECRET_KEY = config('SECRET_KEY')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = config('DEBUG', cast=bool)

# الدومين/الدومينات الحقيقية بتتحدد وقت التشغيل من .env، مش هنا في الكود.
# ده معناه إنك تقدر تغيّر الدومين أو تضيف واحد جديد (أو تشغّل على IP مباشرة)
# من غير ما تلمس settings.py خالص ولا تعمل --build تاني — بس تعدّل .env.production
# وتعمل `docker compose -p mgpharmacy restart web-store web-staff` (وceleryworker
# لو حبيت، بس مش لازم تقنيًا — الإعداد ده مش بيتقرا غير وقت تعامل مع طلبات HTTP).
#
# القيمة في .env بتبقى قائمة مفصولة بفواصل، مثلاً:
#   EXTRA_ALLOWED_HOSTS=biozone.example.com,www.biozone.example.com
#   EXTRA_CSRF_TRUSTED_ORIGINS=https://biozone.example.com,https://www.biozone.example.com
# لو الدومين لسه مش متحدد (زي دلوقتي)، سيبها فاضية في .env وهيفضل شغال
# بالإعدادات الافتراضية (localhost:8081 + أي *.trycloudflare.com) زي ما هو دلوقتي.
# ملحوظة MG Pharmacy: البورت هنا (8081) مختلف عمدًا عن بورت Biozone الأصلي
# (8080) — لو غيّرت بورت الـ host في docker-compose.yml مستقبلًا، لازم
# تحدّث CSRF_TRUSTED_ORIGINS تحت بنفس البورت الجديد، وإلا أي فورم (تسجيل
# دخول/تسجيل حساب/checkout) هيترفض بخطأ CSRF عند الوصول عن طريق البورت الجديد.
_extra_hosts = config('EXTRA_ALLOWED_HOSTS', default='')
_extra_csrf = config('EXTRA_CSRF_TRUSTED_ORIGINS', default='')

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".trycloudflare.com",
] + [h.strip() for h in _extra_hosts.split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    "https://*.trycloudflare.com",
    "http://localhost:8081",
    "http://127.0.0.1:8081",
] + [o.strip() for o in _extra_csrf.split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    # 'daphne' لازم يكون أول حاجة في القايمة (قبل حتى django.contrib.admin) —
    # ده مش تفضيل ترتيب عادي، ده شرط من مكتبة Channels نفسها عشان يستبدل
    # أمر `runserver` بنسخة بتفهم WebSocket (مفيد لو حبيت تجرب بسرعة بره
    # docker compose؛ الإنتاج الفعلي بيشغل daphne/uvicorn مباشرة مش runserver).
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # مطلوب لـ GinIndex في products/models.py (بحث المتجر اللايف — راجع
    # ميجريشن products/0019). ميضيفش جداول ولا فيه أي views/models خاصة
    # بيه إحنا مستخدمينها، هو بس بيسجّل الـ checks/features بتاعة Postgres.
    'django.contrib.postgres',
    'accounts',
    'products',
    'inventory',
    'staff',
    'store',
    'orders',
    'invoices',
    'accounting',
    'notifications',
    'activity',
    'tags',
    'studio',
    'followups',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'config.middleware.NoBrowserCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# django-debug-toolbar للتطوير المحلي بس (عشان نكشف N+1 وأي queries زيادة).
# بيتفعّل بس لو DEBUG=True وموجودة فعليًا في requirements-dev.txt، فمستحيل
# تتحمّل أو تشتغل في الإنتاج على Render حتى لو حد نسي وسابها بالغلط.
if DEBUG:
    try:
        import debug_toolbar  # noqa: F401
        INSTALLED_APPS += ['debug_toolbar']
        MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
        INTERNAL_IPS = ['127.0.0.1']
    except ImportError:
        pass

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notifications',
                'orders.context_processors.site_config',
                'orders.context_processors.cart_count',
                'store.context_processors.new_arrivals_count',
                'staff.context_processors.staff_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='biozone'),
        'USER': config('DB_USER', default='biozone'),
        'PASSWORD': config('DB_PASSWORD', default='changeme'),
        'HOST': config('DB_HOST', default='db'),
        'PORT': config('DB_PORT', default='5432'),
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=60, cast=int),
        # Required whenever Django sits behind PgBouncer in
        # pool_mode=transaction (our default in production — see
        # pgbouncer/pgbouncer.ini): a server-side cursor opened by one
        # query can end up read on a different pooled connection than the
        # one it was opened on, since PgBouncer is free to hand the
        # underlying Postgres connection to a different client between
        # transactions. Nothing in this codebase uses .iterator() today,
        # but this stays on as a safety net for whoever adds it later —
        # without it, that would fail silently/intermittently rather than
        # with a clear error.
        'DISABLE_SERVER_SIDE_CURSORS': True,
    }
}

# Cache (Redis)
# REDIS_URL افتراضيًا بتشاور على اسم السيرفس "redis" في docker-compose
# (شبكة الـ compose بتعمل DNS تلقائي بالاسم ده). لو Redis واقع أو مش
# متاح، Django هيرمي استثناء وقت أي عملية cache بدل ما يتجاهلها بصمت —
# كده أي مشكلة في الاتصال هتظهر فورًا وقت الاختبار المحلي.
REDIS_URL = config('REDIS_URL', default='redis://redis:6379/1')
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
    }
}

# السيشن بتتخزن في Redis (عبر الكاش أعلاه) بدل الداتابيز مباشرة —
# cached_db بتحاول تقرا من الكاش الأول (سريع)، ولو مش موجودة (خرجت من
# الكاش بأي سبب) بترجع تقرا من الداتابيز كـ fallback بدل ما تضيع السيشن
# خالص، عكس backend الكاش الصرف (.cache) اللي كان ممكن يخسر السيشن نهائي
# لو الكاش اتصفّر.
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

# قناة الإشعارات اللحظية (Django Channels) — بتستخدم Redis كـ pub/sub بين
# عمليات gunicorn المختلفة (worker واحد ممكن يكون فاتح WebSocket لمستخدم،
# وworker تاني هو اللي بينفذ notify() لما حدث يحصل — لازم يقدروا يتكلموا
# مع بعض). قاعدة بيانات منفصلة (رقم 2) عن الكاش/السيشن (رقم 1) عمدًا،
# عشان لو حصل يومًا FLUSHDB غلط على واحدة منهم، متأثرش على التانية.
REDIS_CHANNEL_URL = config('REDIS_CHANNEL_URL', default='redis://redis:6379/2')
ASGI_APPLICATION = 'config.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_CHANNEL_URL],
        },
    },
}

# Celery — بينفّذ العمليات الطويلة في worker منفصل تمامًا عن Gunicorn، عشان
# طلب HTTP يرجع فورًا بدل ما ياخد worker كامل لمدة طويلة. نفس Redis
# المستخدم أصلاً، بس قاعدة بيانات رقم 3 منفصلة عن الكاش/السيشن (1) وقناة
# الإشعارات (2). منقول من Biozone — راجع config/celery.py لملحوظة إن مفيش
# tasks فعلية مسجّلة لسه في MG Pharmacy.
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://redis:6379/3')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://redis:6379/3')
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
# حد أقصى مطلق لأي مهمة — حماية من مهمة عالقة تشغل الـ worker للأبد.
CELERY_TASK_TIME_LIMIT = 15 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 10 * 60

# توجيه مهمة النسخ الاحتياطي لطابور منفصل (backup) عن باقي المهام (استيراد/
# تصدير المنتجات والتقارير، ونشر الإشعارات) اللي فاضلة على الطابور
# الافتراضي 'celery'. قبل كده كل حاجة كانت بتتصف في نفس الطابور على نفس
# الـworker (CELERY_CONCURRENCY=1 في docker-compose.yml)، فنسخة احتياطية
# طويلة (dump + رفع لسحابة خارجية عبر rclone، راجع staff/services/backup.py)
# كانت ممكن تأخر استيراد أو تصدير موظف تاني مستني في نفس الطابور خلفها —
# البند 7 من PROJECT_ANALYSIS_REPORT.md. الطابور ده بيتستهلك من worker
# منفصل تمامًا (celery-worker-backup في docker-compose.yml)، مش من نفس
# الـworker بتاع celery-worker — راجع entrypoint.sh (CELERY_QUEUES).
CELERY_TASK_ROUTES = {
    'staff.tasks.run_backup_task': {'queue': 'backup'},
}

# رقم/أرقام تليفون تظهر في ترويسة الفاتورة المطبوعة (راجع
# invoices/templates/invoices/print.html وinvoices/views.py). فاضية
# افتراضيًا عمدًا — قبل كده كان الرقم متكتوب صريح في القالب وكان لسه
# أرقام Biozone القديمة (010 555 46 330 / 01556462929 — 01101551533)
# مش أرقام MG Pharmacy الحقيقية. متعرفش هنا القيمة الصح، فبدل ما نحط رقم
# تاني غلط، الإعداد ده بيتحدد من .env، والقالب مبيعرضش السطر ده خالص لو
# فاضي (بدل ما يعرض رقم فاضي أو placeholder غريب).
INVOICE_COMPANY_PHONE = config('INVOICE_COMPANY_PHONE', default='')

 #----- الإيميل (لازم لإرسال روابط إعادة تعيين كلمة السر) -----
# EMAIL_BACKEND الافتراضي بيطبع الإيميل في الـ console (docker compose logs -f web-store)
# ده مفيد جدًا للتجربة المحلية من غير ما تحتاج SMTP حقيقي.
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='MG Pharmacy <no-reply@mgpharmacy.local>')

# رابط إعادة التعيين صالح لمدة ساعة واحدة بس (بالثواني)
PASSWORD_RESET_TIMEOUT = 60 * 60


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Hasher أخف من الـ default (1.2M iteration في Django 6.0) — منقول من
# Biozone. راجع accounts/hashers.py لملحوظة إن الرقم متقاس على هاردوير
# Biozone مش هاردوير MG Pharmacy، ولازم يتراجع بعد النشر الفعلي.
PASSWORD_HASHERS = [
    'accounts.hashers.FastPBKDF2Hasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# مجلد static/ على مستوى المشروع بيحتوي على tailwind.css المبني (من frontend/input.css
# عن طريق tailwind.config.js) — مش تابع لأي app بعينها، فلازم يتحدد صراحة هنا.
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise: بيقدّم الملفات الثابتة مباشرة من Django/gunicorn، ده بديل
# nginx على منصات زي Render اللي مبتدعمش حاوية nginx منفصلة. الميزة إن
# الملفات بتتضغط تلقائيًا وبتاخد اسم فيه hash عشان الكاش يبقى دايم وآمن.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# الوضع الافتراضي (manifest_strict=True) بيخلي collectstatic يفشل بالكامل
# برمي MissingFileError لو أي ملف CSS/JS بيشاور على مسار static تاني (زي
# `//# sourceMappingURL=...` في نهاية ملف مضغوط) والملف ده مش موجود وقت
# التجميع — حتى لو الملف الناقص ده مش مستخدم فعليًا في أي صفحة. المشكلة إن
# entrypoint.sh بيشغّل collectstatic --clear تحت `set -e` عند *كل* نشر،
# فأي مرجع static ناقص أو اتغيّر اسمه بيوقف تشغيل الحاوية بالكامل والموقع
# كله بيقع لحد ما حد يلاحظ ويصلحها يدويًا — جرّبتها فعليًا بحذف ملف
# chart.umd.min.js.map وأكدت الفشل الكامل، وبعد الإعداد ده تأكدت إنه بقى
# مجرد warning (Django check W004) وباقي كل الملفات بتتجمّع عادي.
WHITENOISE_MANIFEST_STRICT = False

AUTH_USER_MODEL = 'accounts.User'

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
LOGIN_URL = '/accounts/login/'

# حد أقصى لحجم بيانات الطلب غير الملفات (حقول الفورم/JSON) — حماية إضافية
# ضد طلب بحقول نصية ضخمة بالغلط أو مقصود. مهم توضيح: الإعداد ده *مبيحددش*
# سقف لحجم الملفات المرفوعة نفسها (صور المنتجات...) — دي بتتضبط صراحةً عن
# طريق validator على مستوى الموديل (راجع products.validators.validate_image_size)
# لأن دجانجو مفيهوش حد افتراضي لحجم ملف مرفوع.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024  # فوق كده يتكتب لملف مؤقت على القرص بدل الميموري

# إعدادات أمان تُفعَّل فقط لما يكون فيه HTTPS حقيقي قدام السيرفر (شهادة
# فعلية على الدومين). في الاختبار المحلي (docker-compose بدون شهادة) سيبها
# على القيمة الافتراضية False عن طريق .env. لما يبقى عندك دومين + شهادة
# فعلية على السيرفر الحقيقي، حط USE_HTTPS_SECURITY=True في .env بتاعه.
USE_HTTPS_SECURITY = config('USE_HTTPS_SECURITY', default=False, cast=bool)
# لازم يكون موجود قبل أي USE_HTTPS_SECURITY=True حقيقي: nginx بيبعت
# X-Forwarded-Proto (راجع nginx/nginx.conf)، لكن Django مش بيثق فيه تلقائيًا.
# من غير السطر ده، أول ما SECURE_SSL_REDIRECT يتفعّل، Django هيفتكر إن كل
# طلب جاي http (حتى لو أصله https من كلودفلير) ويعمل redirect loop لا نهائي.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = USE_HTTPS_SECURITY
SESSION_COOKIE_SECURE = USE_HTTPS_SECURITY
CSRF_COOKIE_SECURE = USE_HTTPS_SECURITY
SECURE_HSTS_SECONDS = 31536000 if USE_HTTPS_SECURITY else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = USE_HTTPS_SECURITY
SECURE_HSTS_PRELOAD = USE_HTTPS_SECURITY

# Content-Security-Policy (Django 6 native دعم — راجع django.middleware.csp
# و django.utils.csp.CSP فوق). htmx/Alpine/Chart.js وخط Cairo كلهم بقوا
# ملفات محلية (static/js/, static/fonts/) بدل CDN خارجي، فمفيش أي مصدر
# خارجي فعلي محتاج يتضاف هنا دلوقتي. لو ضفت CDN جديد لأي صفحة بعدين، لازم
# يتضاف هنا برضه وإلا هيتحظر صامت من المتصفح.
#
# ملحوظتين مهمين عن التنازلات هنا:
# 1) 'unsafe-inline' في script-src/style-src لسه موجودة لأن فيه <script>
#    و style="" inline متناثرة في تمبلتات كتير (توست، تقارير، فورم
#    المنتجات...) — إزالتها محتاجة نقل كل السكريبتات دي لملفات خارجية أو
#    nonce على كل واحد فيهم، شغلانة أكبر من مجرد إضافة الهيدر. أهم حاجة
#    دلوقتي إن الهيدر موجود ومحدد المصادر المسموحة، بدل مفيش حماية خالص.
# 2) 'unsafe-eval' في script-src لازمة لـ Alpine.js (بيستخدم Function()
#    داخليًا يقيّم تعبيرات زي x-data="{ open: false }")، إلا لو اتحول
#    لنسخة alpinejs/csp المخصصة (بتقيّد x-data بمكونات مسجّلة بس، هتكسر
#    كل الاستخدامات الحالية البسيطة).
SECURE_CSP = {
    "default-src": [CSP.SELF],
    "script-src": [CSP.SELF, CSP.UNSAFE_INLINE, CSP.UNSAFE_EVAL],
    "style-src": [CSP.SELF, CSP.UNSAFE_INLINE],
    "font-src": [CSP.SELF],
    "img-src": [CSP.SELF, "data:"],
    "connect-src": [CSP.SELF],
    "object-src": [CSP.NONE],
    "base-uri": [CSP.SELF],
    "form-action": [CSP.SELF],
    # مفيش أي حد شرعي غير موقعنا نفسه محتاج يعمل iframe لصفحاته — نفس تأثير
    # X-Frame-Options: DENY الموجود أصلًا، بس بمعيار CSP الأحدث.
    "frame-ancestors": [CSP.NONE],
}


# ============================================================================
# Logging — شغال دايمًا محليًا (مش محتاج أي خدمة خارجية ولا حساب).
# بيكتب الأخطاء (WARNING فما فوق) في ملف داخل logs/ جوه الحاوية، ومربوط بـ
# volume في docker-compose.yml عشان الملف يفضل موجود حتى لو الحاوية اتعملها
# rebuild أو restart. بيتقلب تلقائيًا (rotate) لما يوصل 5 ميجا، ومحتفظ بآخر
# 5 نسخ بس عشان القرص متمتلاش.
# ============================================================================
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 5 * 1024 * 1024,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'WARNING',
        },
    },
    'root': {
        'handlers': ['console', 'error_file'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            # الأخطاء الفعلية اللي بتطلع 500 للمستخدم (exceptions جوه الـ views).
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # urllib3 (وبالتبعية sentry_sdk، اللي بيستخدمه جوه لإرسال الأحداث)
        # بيكتب WARNING متكرر جدًا لو السيرفر مش عنده وصول شبكة/DNS لدومين
        # Sentry (زي ما حصل فعليًا يوم 2026-08-06 — آلاف الأسطر ملّت
        # errors.log خلال ساعات وعملت rotation متكرر، وكانت كلها ضجيج شبكة
        # مش أخطاء حقيقية في التطبيق). بنسيبها تظهر في console (تفيد وقت
        # docker compose logs) بس منمنعها توصل لـ error_file عشان الملف
        # يفضل مخصص لأخطاء التطبيق الفعلية بس. ده منفصل تمامًا عن نجاح/فشل
        # Sentry نفسه — لو عايز Sentry يشتغل فعلاً، الحل هو فتح وصول الشبكة
        # له، مش ده.
        'urllib3': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# ============================================================================
# Sentry — اختياري تمامًا ومطفي افتراضيًا. بيشتغل بس لو حطيت SENTRY_DSN في
# .env.production. لو سيبتها فاضية (زي دلوقتي)، السطر ده مبيعملش حاجة خالص
# والمشروع بيفضل معتمد على الـ logging المحلي بس.
# sentry-sdk متضاف في requirements.txt جاهز، فمش محتاج --build إضافي غير
# وقت أول مرة بس. تفعيله الفعلي = بس تحط SENTRY_DSN في .env.production.
# ============================================================================
SENTRY_DSN = config('SENTRY_DSN', default='')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=config('SENTRY_TRACES_SAMPLE_RATE', default=1.0, cast=float),
        send_default_pii=False,
        environment=config('SENTRY_ENVIRONMENT', default='production'),
    )
