# Generated by Django 6.0.6 on 2026-07-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='public_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
