# Generated by Django 6.0.6 on 2026-08-10 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_is_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PRE_DELIVERY', 'قبل التسليم'), ('POST_DELIVERY', 'بعد التسليم')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'إشعار إلغاء فاتورة',
                'verbose_name_plural': 'إشعارات إلغاء الفواتير',
                'ordering': ['-created_at'],
            },
        ),
    ]
