# Generated by Django 6.0.6 on 2026-08-11 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoicereversal'),
        ('orders', '0014_orderitem_scanned_orderitem_scanned_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicereversal',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار مرتجع', 'verbose_name_plural': 'إشعارات المرتجع'},
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='invoicereversal',
            name='return_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30),
        ),
        migrations.CreateModel(
            name='InvoiceReversalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversal_items', to='invoices.invoiceitem')),
                ('reversal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoicereversal')),
            ],
            options={
                'verbose_name': 'صنف في إشعار المرتجع',
                'verbose_name_plural': 'أصناف إشعارات المرتجع',
            },
        ),
    ]
