# Generated by Django 6.0.6 on 2026-07-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_businesstypesetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='custom_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='اترك هذا الحقل فارغًا ليحصل الحساب على النسبة الافتراضية لنوع النشاط.', max_digits=5, null=True, verbose_name='نسبة خصم مخصصة لهذا الحساب (%)'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='is_wholesale_override',
            field=models.BooleanField(blank=True, help_text='اترك هذا الحقل فارغًا إذا كان الحساب يتبع إعداد نوع النشاط تلقائيًا.', null=True, verbose_name='تخصيص جملة/قطاعي لهذا الحساب'),
        ),
    ]
