# Generated by Django 6.0.6 on 2026-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_clientprofile_custom_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_accounting',
            field=models.BooleanField(default=False, help_text='الأدمن دايمًا عنده وصول كامل للقسم المالي بغض النظر عن هذا الحقل. فعّل هذا الحقل لو عايز تسمح لحساب مخزن معيّن بالوصول للقسم المالي.', verbose_name='صلاحية الوصول للقسم المالي'),
        ),
    ]
