# Generated by Django 6.0.6 on 2026-07-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_access_accounting',
            field=models.BooleanField(default=False, help_text='حقل قديم — استُبدل بنظام الصلاحيات الدقيق (staff.permissions.PERMISSION_SECTIONS). اترك القيمة الافتراضية ومنّح صلاحية "الحسابات" من شاشة تعديل الموظف بدلًا منه.', verbose_name='صلاحية الوصول للقسم المالي (قديم)'),
        ),
    ]
