# Generated by Django 6.0.6 on 2026-07-15 08:59
# تم تعديله يدويًا: قبل ما نخلي الإيميل unique، لازم نعالج أي إيميلات فاضية
# أو مكررة موجودة فعليًا في قاعدة البيانات، وإلا الـ unique constraint
# هيفشل (زي ما حصل فعليًا مع مستخدمين بإيميل فاضي مكرر).

from django.db import migrations, models


def dedupe_emails(apps, schema_editor):
    """
    أي مستخدم إيميله فاضي، أو إيميله مكرر مع مستخدم قبله، بناخده إيميل
    placeholder فريد مبني على username (مش هيتبعت له أي حاجة فعليًا،
    بس عشان الـ unique constraint يعدي من غير ما نفقد أي حساب أو نضطر
    نحذفه). المستخدم يقدر يحدّث إيميله الحقيقي بعد كده عادي.
    """
    User = apps.get_model('accounts', 'User')
    seen = set()
    for user in User.objects.all().order_by('id'):
        email = (user.email or '').strip()
        if not email or email in seen:
            placeholder = f'{user.username}@noemail.biozone.local'
            # احتياطًا لو حتى الـ placeholder ده مكرر (username غريب)
            suffix = 1
            candidate = placeholder
            while candidate in seen or User.objects.filter(email=candidate).exclude(pk=user.pk).exists():
                candidate = f'{user.username}+{suffix}@noemail.biozone.local'
                suffix += 1
            user.email = candidate
            user.save(update_fields=['email'])
            seen.add(candidate)
        else:
            seen.add(email)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_can_access_accounting'),
    ]

    operations = [
        migrations.RunPython(dedupe_emails, noop_reverse),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
