# Generated by Django 6.0.6 on 2026-07-15 09:15
# تم تعديله يدويًا لإضافة داتا مايجريشن تحافظ على البيانات القديمة قبل حذف
# business_type/BusinessTypeSetting القديمين (شوف migrate_business_type_data تحت).

import django.db.models.deletion
from django.db import migrations, models


# نفس التسميات العربية القديمة لأنواع النشاط (business_type) — بنعتمد عليها
# بس عشان نولّد أنواع الحسابات المكافئة تلقائيًا ونهجّر بيانات العملاء
# الحاليين من غير أي فقد، قبل ما نحذف الحقول القديمة نهائيًا.
LEGACY_TYPE_NAMES = {
    'PHARMACY': 'صيدلية',
    'HOSPITAL': 'مستشفى',
    'CLINIC': 'عيادة',
    'OTHER': 'أخرى',
}
WHOLESALE_TYPE_NAME = 'جملة'


def migrate_business_type_data(apps, schema_editor):
    """
    بيهجّر كل ClientProfile موجود من نظام business_type/BusinessTypeSetting/
    is_wholesale_override/custom_discount_percent القديم إلى نوع حساب واحد
    (account_type) مكافئ:
      - لو الحساب كان "جملة فعليًا" (override صريح، أو تبعية لنوع نشاطه
        العام لو مفيش override) → بيتحول لنوع حساب "جملة" (وحدة كبرى افتراضيًا).
      - غير كده → بيتحول لنوع الحساب المكافئ لنوع نشاطه القديم (صيدلية/
        مستشفى/عيادة/أخرى)، بوحدة صغرى افتراضيًا (سلوك القطاعي القديم).
    نسبة الخصم المخصصة القديمة (لو موجودة) مش بتتهجّر تلقائيًا لقائمة خصومات
    الأصناف الجديدة، لأنها كانت نسبة عامة على كل الأصناف — الأدمن لازم يحدد
    قائمة الخصومات الجديدة يدويًا من شاشة "أنواع الحسابات" بعد الترقية.
    """
    AccountType = apps.get_model('accounts', 'AccountType')
    ClientProfile = apps.get_model('accounts', 'ClientProfile')
    BusinessTypeSetting = apps.get_model('accounts', 'BusinessTypeSetting')

    type_objs = {}
    for code, name in LEGACY_TYPE_NAMES.items():
        obj, _ = AccountType.objects.get_or_create(name=name, defaults={'default_unit_size': 'S'})
        type_objs[code] = obj

    wholesale_type, _ = AccountType.objects.get_or_create(
        name=WHOLESALE_TYPE_NAME, defaults={'default_unit_size': 'L'},
    )

    settings_by_code = {s.business_type: s for s in BusinessTypeSetting.objects.all()}

    for profile in ClientProfile.objects.all():
        if profile.is_wholesale_override is True:
            is_wholesale = True
        elif profile.is_wholesale_override is False:
            is_wholesale = False
        else:
            setting = settings_by_code.get(profile.business_type)
            is_wholesale = bool(setting and setting.is_wholesale)

        profile.account_type = (
            wholesale_type if is_wholesale
            else type_objs.get(profile.business_type, type_objs['OTHER'])
        )
        profile.save(update_fields=['account_type'])


def noop_reverse(apps, schema_editor):
    # مفيش رجوع تلقائي لتفاصيل الخصم القديمة (كانت عامة، بقت لكل صنف) —
    # لو احتجت rollback فعلي، هيتطلب تدخل يدوي.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم نوع الحساب')),
                ('default_unit_size', models.CharField(choices=[('S', 'صغرى'), ('L', 'كبرى')], default='S', help_text='الوحدة (صغرى/كبرى) التي تظهر في المتجر لأي عميل من هذا النوع.', max_length=1, verbose_name='الوحدة الافتراضية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوع حساب',
                'verbose_name_plural': 'أنواع الحسابات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='account_type',
            field=models.ForeignKey(help_text='يحدد الوحدة الظاهرة في المتجر وقائمة الخصومات المطبّقة على هذا الحساب.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_profiles', to='accounts.accounttype', verbose_name='نوع الحساب'),
        ),
        migrations.RunPython(migrate_business_type_data, noop_reverse),
        migrations.RemoveField(
            model_name='clientprofile',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='custom_discount_percent',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='is_wholesale_override',
        ),
        migrations.DeleteModel(
            name='BusinessTypeSetting',
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='account_type',
            field=models.ForeignKey(help_text='يحدد الوحدة الظاهرة في المتجر وقائمة الخصومات المطبّقة على هذا الحساب.', on_delete=django.db.models.deletion.PROTECT, related_name='client_profiles', to='accounts.accounttype', verbose_name='نوع الحساب'),
        ),
    ]
