# Generated by Django 6.0.6 on 2026-07-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productunit_wholesale_min_qty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ['qty_in_small'], 'verbose_name': 'وحدة', 'verbose_name_plural': 'الوحدات'},
        ),
        migrations.AddField(
            model_name='productunit',
            name='allow_split',
            field=models.BooleanField(default=False, help_text='يُفعّل بس على الوحدة الكبرى لمنتج بوحدة واحدة (زي كرتونة سرنجات). لو مفعّل: القطاعي (بس) يقدر يطلب قطع مفردة مقصوصة من جوه الوحدة دي، بسعر متناسب (سعر الوحدة ÷ عدد القطع فيها). الجملة بتفضل تطلب الوحدة كاملة زي ما هي، مهما كان هذا الخيار مفعّل أو لأ.', verbose_name='قابل للتجزئة'),
        ),
    ]
