# Generated by Django 6.0.6 on 2026-07-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productunit_options_productunit_allow_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='size',
            field=models.CharField(choices=[('S', 'صغرى'), ('L', 'كبرى')], max_length=1),
        ),
    ]
