# Generated by Django 6.0.6 on 2026-07-05 09:08

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productunit_allow_split'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productunit',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('product', 'size'), name='products_productunit_product_size_uniq'),
        ),
    ]
