# Generated by Django 6.0.6 on 2026-07-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accounttype_delete_businesstypesetting_and_more'),
        ('products', '0009_alter_productunit_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='تُطرح من سعر الجمهور (unit_price) لهذا الصنف تحديدًا، لهذا النوع من الحسابات.', max_digits=5, verbose_name='نسبة الخصم (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_discounts', to='accounts.accounttype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.productunit')),
            ],
            options={
                'verbose_name': 'خصم صنف لنوع حساب',
                'verbose_name_plural': 'خصومات الأصناف لأنواع الحسابات',
                'constraints': [models.UniqueConstraint(fields=('unit', 'account_type'), name='products_unitdiscount_unit_accounttype_uniq')],
            },
        ),
    ]
