# Generated by Django 6.0.6 on 2026-07-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_new_arrival_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='باركود العبوة (اختياري) — يمكن مسحه بقارئ الباركود عند البحث في المخزون', max_length=64, null=True, unique=True, verbose_name='الباركود'),
        ),
    ]
