# Generated by Django 6.0.6 on 2026-07-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='سعر شراء هذه الوحدة (يُستخدم في حساب الربح بتقارير المبيعات). اتركه صفرًا لو غير معروف حاليًا.', max_digits=10, verbose_name='سعر التكلفة'),
        ),
    ]
