# Generated by Django 6.0.6 on 2026-08-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_product_name_ar_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_2',
            field=models.CharField(blank=True, db_index=True, help_text='باركود إضافي اختياري لنفس الصنف (تغليف مختلف مثلًا)', max_length=64, null=True, unique=True, verbose_name='باركود إضافي (٢)'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_3',
            field=models.CharField(blank=True, db_index=True, help_text='باركود إضافي اختياري لنفس الصنف (تغليف مختلف مثلًا)', max_length=64, null=True, unique=True, verbose_name='باركود إضافي (٣)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, error_messages={'unique': 'هذا الكود مستخدم بالفعل لمنتج آخر — اختر كودًا مختلفًا أو اتركه فارغًا ليتولّد تلقائيًا.'}, help_text='كود الصنف الأساسي — اتركه فارغًا ليتولّد تلقائيًا (BZ-00001...)، أو ادخل كود المورّد/الترقيم الداخلي الخاص بك.', max_length=20, unique=True, verbose_name='الكود'),
        ),
    ]
