# Generated by Django 6.0.6 on 2026-08-06 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_barcode_2_product_barcode_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='ProductVariantGroup',
        ),
    ]
