# Generated by Django 6.0.6 on 2026-08-12 (يدوي — راجع STUDIO_PLAN.md، المرحلة 8)
#
# بتحوّل Category.image وProduct.image من ImageField مباشر لـ ForeignKey
# على studio.StudioImage — قرار رقم 7 في الخطة. SET_NULL (مش CASCADE ولا
# PROTECT) عشان حذف صورة من الاستوديو ميفشلش ولا يمسح المنتج/القسم
# المرتبط، الربط بس بيختفي (نفس سلوك StudioImage.folder، راجع migration
# 0002 في studio). مفيش RunPython/data migration هنا: مفيش صور Product/
# Category موجودة فعليًا وقت التنفيذ (قرار رقم 10 في الخطة) — الحقل
# القديم كان ImageField بيتخزن كملف على الـ filesystem/storage مباشرة
# بلا صف قاعدة بيانات في studio.StudioImage نقدر نربطه بيه تلقائيًا، فمفيش
# تحويل ممكن أصلًا حتى لو كان فيه صور، وده بالظبط سبب القرار إن الحقل
# يبدأ فاضي (null) للكل بعد الترقية.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_variant_group_remove_product_size_and_more'),
        ('studio', '0002_studiofolder_studioimage_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='categories',
                to='studio.studioimage',
                verbose_name='صورة القسم',
            ),
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products',
                to='studio.studioimage',
                verbose_name='صورة المنتج',
            ),
        ),
    ]
