# Generated by Django 6.0.6 on 2026-06-30 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='أقل قيمة إجمالية مسموح بها لإرسال الطلب (بالجنيه). اتركها صفر لو مش عايز حد أدنى.', max_digits=10, verbose_name='الحد الأدنى لقيمة الطلب')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('CREATED', 'تم إنشاء الطلب'), ('STATUS_CHANGED', 'تغيير الحالة'), ('NOTE', 'ملاحظة')], max_length=20)),
                ('new_status', models.CharField(blank=True, choices=[('PENDING', 'في الانتظار'), ('CONFIRMED', 'مؤكد'), ('REJECTED', 'مرفوض'), ('DELIVERED', 'تم التسليم')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'سجل عملية',
                'verbose_name_plural': 'سجل العمليات',
                'ordering': ['created_at'],
            },
        ),
    ]
