# Generated by Django 6.0.6 on 2026-06-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_siteconfig_orderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'في الانتظار'), ('NEEDS_APPROVAL', 'بانتظار موافقتك على التعديل'), ('CONFIRMED', 'مؤكد'), ('REJECTED', 'مرفوض'), ('DELIVERED', 'تم التسليم')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='new_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'في الانتظار'), ('NEEDS_APPROVAL', 'بانتظار موافقتك على التعديل'), ('CONFIRMED', 'مؤكد'), ('REJECTED', 'مرفوض'), ('DELIVERED', 'تم التسليم')], max_length=20),
        ),
    ]
