# Generated by Django 6.0.6 on 2026-06-30 04:37

from django.db import migrations
from django.db.models import F


def backfill_originals(apps, schema_editor):
    """
    الطلبات القديمة اللي اتعملت قبل إضافة original_quantity/original_unit_price
    كانت لسه متعدلة (مفيش staff لمسها)، فالقيمة الحالية = القيمة الأصلية فعليًا.
    لو سيبناها None، أول تعديل من المخزن كان هيغلط ويعتبر القيمة المعدّلة هي الأصل.
    """
    OrderItem = apps.get_model('orders', 'OrderItem')
    OrderItem.objects.filter(original_quantity__isnull=True).update(original_quantity=F('quantity'))
    OrderItem.objects.filter(original_unit_price__isnull=True).update(original_unit_price=F('unit_price'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_original_quantity_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_originals, noop),
    ]
