# Generated by Django 6.0.6 on 2026-07-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderitem_purchase_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='أقل قيمة إجمالية مسموح بها لإرسال الطلب (بالجنيه). اترك القيمة صفرًا في حال عدم الرغبة في تحديد حد أدنى.', max_digits=10, verbose_name='الحد الأدنى لقيمة الطلب'),
        ),
    ]
