# Generated by Django 6.0.6 on 2026-07-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_siteconfig_min_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='public_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
