# Generated by Django 6.0.6 on 2026-07-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='viewed_by_staff',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
