# Generated by Django 6.0.6 on 2026-08-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_min_order_amount_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='scanned',
            field=models.BooleanField(default=False, verbose_name='اتفحص بالسكانر'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الفحص'),
        ),
    ]
