# Generated by Django 6.0.6 on 2026-08-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_scanned_orderitem_scanned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم المستلم'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم هاتف التواصل'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='عنوان التوصيل'),
        ),
    ]
