# Generated by Django 6.0.6 on 2026-08-29 15:28

import orders.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_prescriptionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=orders.storage.PrescriptionImageStorage(), upload_to='%Y/%m/', verbose_name='صورة الروشتة'),
        ),
    ]
