# Generated by Django 6.0.6 on 2026-08-11 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('invoices', '0004_invoicereversal'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='invoice_reversal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_transactions', to='invoices.invoicereversal'),
        ),
    ]
