# Generated by Django 6.0.6 on 2026-07-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_rename_name_product_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='wholesale_min_qty',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='wholesale_mode',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='wholesale_price',
        ),
    ]
