# Generated by Django 6.0.6 on 2026-07-19 10:12

import django.core.validators
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), products.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), products.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
    ]
