# Generated by Django 6.0.6 on 2026-07-28 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productunit_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(blank=True, help_text='اختياري — للتمييز في لوحة الإدارة فقط، لا يظهر للعميل', max_length=255, verbose_name='اسم داخلي (للإدارة فقط)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مجموعة مقاسات',
                'verbose_name_plural': 'مجموعات المقاسات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='complementary_products',
            field=models.ManyToManyField(blank=True, related_name='complementary_of', to='products.product', verbose_name='منتجات مكمّلة'),
        ),
        migrations.AddField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, related_name='similar_of', to='products.product', verbose_name='منتجات مشابهة'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='مقاس المنتج (لبس/هدوم) إن وجد — غير حجم الوحدة (قطعة/كرتونة) تمامًا', max_length=50, verbose_name='المقاس'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productvariantgroup', verbose_name='مجموعة المقاسات'),
        ),
    ]
