# Generated by Django 6.0.6 on 2026-08-01 16:50
#
# ملحوظة: ميجريشن خاص بـ Postgres بس (زي كل الميجريشنز التانية في المشروع،
# راجع DATABASES في settings.py). TrigramExtension بتفعّل pg_trgm أول مرة
# — لازم تتنفذ قبل أي AddIndex بيستخدم gin_trgm_ops، عشان كده مضافة يدويًا
# هنا فوق العمليات اللي Django ولّدها تلقائيًا.

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_productunit_cost_price'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_ar'], name='product_name_ar_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='product_name_en_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_key'], name='product_name_key_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
